### ISSUE TITLE
yan is time-traveller 

### ISSUE THREAD

**Issue by compliment** [diracdeltas/blog#1]
On Monday, 2 April 2018 

[https://diracdeltas.github.io/canary/](https://diracdeltas.github.io/canary/)
says 
> As of 20 December  2018

that's all.

Edit;
[I'm an idiot.](https://i.imgur.com/GNuXMYD.gif)

Warrant canary repo is [here](https://github.com/diracdeltas/canary), not here

**Comment by diracdeltas** [comment]
fixed
